### ISSUE TITLE
Add support for multiple regular expressions in `prune-tags-regexes`

### ISSUE THREAD

**Issue by vlaurin** [vlaurin/action-ghcr-prune#10]
For example:
```yml
steps:
  - name: Prune
    uses: vlaurin/action-ghcr-prune@main
    with:
      token: ${{ secrets.YOUR_TOKEN }}
      organization: your-org
      container: your-container
      prune-tags-regexes: |
        ^pr-
        ^test-
```

Given Github actions currently do not natively support YAML lists as input value, multi-value inputs can be achieved using multi-lines, like it's done in Github's own [actions/cache](https://github.com/actions/cache#whats-new).
This is supported by the action toolkit [getMultilineInput()](https://github.com/actions/toolkit/pull/829).
