### ISSUE TITLE
Package Not Found

### ISSUE THREAD

**Issue by xiabai84** [vlaurin/action-ghcr-prune#22]
Hi, 
Somehow the github-action can't find our package, see my command line output below.
If I understand name of "container" correct, this would be also the name of package, is that right?

Here is my setting:
```
...
- name: Delete all pre-release package versions except latest 5
  uses: vlaurin/action-ghcr-prune@v0.3.0
  with: 
    token: ${{ secrets.GITHUB_TOKEN }}
    organization: my-organization
    container: integrationtest/integrationtest
    older-than: 0 # days
    keep-last: 5
    untagged: false
```

And output:
```
Run vlaurin/action-ghcr-prune@v0.[3](https://github.com/my-organization/integrationtest/runs/5362647101?check_suite_focus=true#step:7:3).0
  with:
    token: ***
    dry-run: true
    organization: my-organization
    container: integrationtest/integrationtest
    keep-last: [5](https://github.com/my-organization/integrationtest/runs/5362647101?check_suite_focus=true#step:7:5)
    older-than: 0
    untagged: false
Crawling through all versions to build pruning list...
Error: Package not found.
```
