### ISSUE TITLE
Add `keep-last` input

### ISSUE THREAD

**Issue by vlaurin** [vlaurin/action-ghcr-prune#4]
Optional input defaulting to `0`. Define the count of qualifying, most recent versions to keep.

### Example

To keep the last 5 untagged versions which are older than 7 days:
```yaml
steps:
  - name: Prune
    uses: vlaurin/action-ghcr-prune@main
    with:
      token: ${{ secrets.YOUR_TOKEN }}
      organization: your-org
      container: your-container
      older-than: 7 # days
      untagged: true
      keep-last: 5
```

**Comment by TROEERI** [comment]
This would be a feature needed to make this action applicable for our use-case.

**Comment by vlaurin** [comment]
@TROEERI I'm still testing it, but if you want to have a go at using it you can do so using my branch:

```yml
      - uses: vlaurin/action-ghcr-prune@4-keep-last
        name: Prune untagged images after 1 day, except 2 most recent
        with:
          token: ${{ secrets.YOUR_TOKEN }}
          organization: your-org
          container: your-container
          dry-run: true
          older-than: 1 # days
          keep-last: 2
          untagged: true
```

Feedback welcome, if all good I can release it today.
