### ISSUE TITLE
HttpError: Package not found

### ISSUE THREAD

**Issue by kyzima-spb** [vlaurin/action-ghcr-prune#64]
Good day.

I tried using your action and got this error: `HttpError: Package not found`

```yml
- uses: vlaurin/action-ghcr-prune@main
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
    user: ${{ github.repository_owner }}
    container: "gui"
    untagged: true
```

**Comment by vlaurin** [comment]
This is most likely a permission issue.

> To use this endpoint, you must authenticate using an access token with the `packages:read` and `packages:delete` scopes.
> In addition:
> [...]
> If `package_type` is container, you must also have admin permissions to the container you want to delete.
source: https://octokit.github.io/rest.js/v18#packages-delete-package-version-for-user

I see that you are using the GitHub-provided `secrets.GITHUB_TOKEN` which I don't believe would ever have admin permissions to a container. I would advise to use a personal access token instead with permissions as per above.

**Comment by kyzima-spb** [comment]
Thanks, it worked with the personal token.

I'm guessing `GITHUB_TOKEN` doesn't have delete-only permissions because adding a new image works (push).

```yml
-
  name: Login to GitHub Container Registry
  uses: docker/login-action@v2
  with:
    registry: ghcr.io
    username: ${{ github.repository_owner }}
    password: ${{ secrets.GITHUB_TOKEN }}
-
  name: Build and push
  uses: docker/build-push-action@v3
  with:
    context: ./docker
    build-args: |
      RELEASE=${{ matrix.release }}
    push: true
    tags: ${{ steps.meta.outputs.tags }}
    labels: ${{ steps.meta.outputs.labels }}
```

**Comment by mill1000** [comment]
If anyone stumbles upon this in 2023, I was able to delete images using my GITHUB_TOKEN.

```yaml
jobs:
  prune-pr-images:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: vlaurin/action-ghcr-prune@v0.5.0
        with:
          container: ${{ env.CONTAINER_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          prune-tags-regexes: ^pr-${{github.event.pull_request.number}}
          # dry-run: true
```
