### ISSUE TITLE
Removing untagged images can damage tagged multi-arch images

### ISSUE THREAD

**Issue by jr01** [vlaurin/action-ghcr-prune#76]
To publish an image we use something like:
```yaml
- uses: docker/build-push-action@v4
  with:
     context: .
     push: true
     tags: |
       my-image: v0.0.1
```

And we were pruning any untagged images with something like:
``` yaml
- uses: vlaurin/action-ghcr-prune@v0.5.0
  with:
     token: ${{ secrets.MY_TOKEN }}
     organization: myorg
     container: mycontainer
     prune-untagged: true
```

We noticed that after pruning a `docker pull ghcr.io/myorg/mycontainer:v0.0.1` would return error: `manifest unknown`.

We found https://github.com/snok/container-retention-policy/issues/63 that explains the issue.

We aren't using multi-arch and can use the `provenance: false` workaround.

**Comment by daltonv** [comment]
I actually do use multi-arch images so this is a problem for me & my team. 

I did fork the repo and add this ability at https://github.com/daltonv/action-ghcr-prune/tree/dv_multi_arch

However I saw the similar #75 was closed due to it being out of scope. My fix is I think a bit more precise and is off by default. I can make a pr, @vlaurin, if you think this is a more maintainable solution.

**Comment by emmahsax** [comment]
@daltonv To clarify, your modification is such that we wouldn't have to tidy up untagged _and_ tagged images. Instead, we should change our code to simply delete any tagged image, and then if it is multi-arch, your change would also delete the untagged images that correspond to it.

Is that correct?

And here's an example of the changes that'd be required:

```diff
  jobs:
-   delete-untagged-packages:
-     runs-on: ubuntu-latest
-     steps:
-       - uses: vlaurin/action-ghcr-prune@v0.6.0
-         with:
-           container: ${{ github.event.repository.name }}
-           dry-run: false
-           keep-last: 12
-           organization: ${{ github.repository_owner }}
-           prune-untagged: true
-           token: ${{ secrets.GITHUB_TOKEN }}
-
    delete-tagged-packages:
      runs-on: ubuntu-latest
      steps:
-       - uses: vlaurin/action-ghcr-prune@v0.6.0
+       - uses: daltonv/action-ghcr-prune@v0.1.0
          with:
            container: ${{ github.event.repository.name }}
            dry-run: false
            keep-last: 5
            keep-tags-regexes: |
              ^latest$
            organization: ${{ github.repository_owner }}
+           prune-multi-platform: true
            prune-tags-regexes: |
              .+
            token: ${{ secrets.GITHUB_TOKEN }}

```

And then even with these changes, when I run it, I get an API failure:

```
Run daltonv/action-ghcr-prune@v0.1.0
  with:
    container: my-repo
    dry-run: true
    keep-last: 0
    keep-tags-regexes: ^latest$
  
    organization: my-org
    prune-multi-platform: true
    prune-tags-regexes: .+
  
    token: ***
    older-than: 0
    keep-younger-than: 0
    prune-untagged: false
    untagged: false
Crawling through all versions to build pruning list...
Found 5 versions to prune out of [2](https://github.com/my-org/my-repo/actions/runs/8635358189/job/23672892553#step:3:2)1 on page 1
Crawling through pruning list for multi-platform images...
Error: Docker API request at https://ghcr.io/v2/my-org/my-repo/manifests/pre-release-d2f02[8](https://github.com/my-org/my-repo/actions/runs/8635358189/job/23672892553#step:3:8)0 was not successful
```

Did I miss something? Am I supposed to use the `${{ secrets.GITHUB_TOKEN }}` or a different PAT?

**Comment by emmahsax** [comment]
I ended up expanding on what @daltonv worked with even further. I adjusted @daltonv's code so that it worked with my images, and then I made it so that when pruning untagged images, it'll never try to prune any image that is a part of a multi-arch image at all: https://github.com/emmahsax/action-ghcr-prune/tree/main

So now, we can call my variation of the action like this:
```yaml
jobs:
  delete-old-packages:
    runs-on: ubuntu-latest
    steps:
      # Delete all tagged packages except `latest` and the last other 5 (so 6 tagged packages left over
      # at the end). Also delete the untagged variants of the tagged packages that are deleted.
      - name: Delete Old Tagged Packages
        uses: emmahsax/action-ghcr-prune@main
        with:
          container: ${{ github.event.repository.name }}
          dry-run: true
          keep-last: 5
          keep-tags-regexes: |
            ^latest$
          organization: ${{ github.repository_owner }}
          prune-tags-regexes: |
            .+
          remove-multi-platform: true
          token: ${{ secrets.GITHUB_TOKEN }}

      # After the first step finishes, then go through and delete all other untagged packages
      # UNLESS they are a part of a multi-arch image that is left around from the first step.
      - name: Delete Old Untagged Packages
        uses: emmahsax/action-ghcr-prune@main
        with:
          container: ${{ github.event.repository.name }}
          dry-run: true
          keep-last: 0
          organization: ${{ github.repository_owner }}
          prune-untagged: true
          token: ${{ secrets.GITHUB_TOKEN }}
```
