### ISSUE TITLE
HttpError: Package not found (not permission issue)

### ISSUE THREAD

**Issue by oerp-odoo** [vlaurin/action-ghcr-prune#79]
I recently noticed that my cron job now constantly fails to prune images. I am getting this error: `Error: Failed to prune because of: HttpError: Package version not found.`

Though I have many jobs, running for different packages to remove images and only some fail. If I later re-run failed jobs, they complete fine. So I guess its related with some timeout issues or something?

![Selection_1061](https://github.com/vlaurin/action-ghcr-prune/assets/7812986/cf4f879c-1c4d-43fd-9afb-b573f8084164)

P.S. I see there was issue regarding same error here: https://github.com/vlaurin/action-ghcr-prune/issues/64 but in my case, it does not look like its access issue.

**Comment by vlaurin** [comment]
Hi @oerp-odoo,

Given there are multiple jobs that seem to be running concurrently, could it be that there's an overlap in the versions being pruned by 2 different jobs?

For example, `prune_images (17.0)` and `prune_images (16.0)` running in parallel; both listing the same versions; but `17.0` having started a few seconds earlier starts pruning first and when `16.0` then tries to prune the packages they've already been removed hence the `Package version not found` error?

You should be able to confirm that by expending the `Pruning x versions...` in the logs and cross-checking version IDs/SHAs for overlap.

**Comment by oerp-odoo** [comment]
@vlaurin you are right, it could be the case. As I am not filtering per `version` and multiple jobs can use same step, so it could get same images:

```yml
      - name: Prune specific ref old images
        uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          token: ${{ secrets.GHCR_DELETE_TOKEN }}
          organization: versada
          container: ${{ matrix.project }}
          dry-run: false
          keep-younger-than: 10
          keep-last: 0
          prune-untagged: false
          prune-tags-regexes: ^ref-.+$
```
I will simplify prune logic and see how it goes. Thanks for suggestions.
