### ISSUE TITLE
404 Package Not Found?

### ISSUE THREAD

**Issue by tibbon** [vlaurin/action-ghcr-prune#8]
I'm getting a 404 on the package deletion, but I'm not sure why. 

```
      - name: GHCR Pruning
        uses: vlaurin/action-ghcr-prune@v0.3
        with:
          token: REDACTED
          organization: my-org
          container: my-private-repo
          dry-run: false # Dry-run first, then change to `false`
          older-than: 0 # days
          keep-last: 3
          untagged: true
```

```
Crawling through all versions to build pruning list...
Found 4 versions to prune out of 10 on page 1
Keeping the last 3 versions, sorted by creation date
Found a total of 1 versions to prune
Pruning 1 versions...
Pruning version ... REDACTED'...
Failed to prune because of:  RequestError [HttpError]: Package not found.
```

The one thing I note is that it's finding the right *name* of one to delete, but not the right ID - assuming the IDs that appear in the UI are the same as the ones targeted here.

I suspect that perhaps I need more permissions on my token, which I'm going to try next. But I'm unsure. Will report back.
